export const iconToImagePath = {
  "01d": "sunny.png",
  "01n": "clear-night.png",
  "02d": "partly-cloudy.png",
  "02n": "partly-cloudy-night.png",
  "03d": "cloudy.png",
  "03n": "cloudy-night.png",
  "04d": "overcast.png",
  "04n": "overcast-night.png",
  "09d": "rainy.png",
  "09n": "rainy-night.png",
  "10d": "rainy2.png",
  "10n": "rainy-night.png",
  "11d": "thunderstorm.png",
  "11n": "thunderstorm-night.png",
  "13d": "snowy.png",
  "13n": "snowy-night.png",
  "50d": "misty.png",
  "50n": "misty-night.png",
};
